server:
  port: 8080


urls:
  avengers: http://www.mocky.io/v2/5ecfd5dc3200006200e3d64b
  antiHeroes: http://www.mocky.io/v2/5ecfd630320000f1aee3d64d
  mutant: http://www.mocky.io/v2/5ecfd6473200009dc1e3d64e